---
title: "HPA_data_v24_2"
output: html_document
date: "2025-02-25"
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(readxl)

manifest <- read_excel("data/samples_2024-12-17.xlsx")
ht_data <- read_csv("data/final_data/wellness_data.csv")
```


# Wellness data

## Metadata

```{r}
# Extract relevant information from Wellness metadata
wellness_meta <- 
  manifest |> 
  filter(Cohort == "WELL") |> 
  select(DAid, Age, Sex, `Extra data`) |> 
  mutate(
    Visit = str_extract(`Extra data`, "(?<=visit: )\\d+"),                   
    Subject = str_extract(`Extra data`, "(?<=subject_id: )\\d+-\\d+")) |> 
  select(-`Extra data`)
```

## Filter data

```{r}
# Filter Wellness data to samples in the metadata
wellness_data <- 
  ht_data |> 
  filter(DAid %in% wellness_meta$DAid) |> 
  select(DAid, OlinkID, Assay, NPX, LOD)
```

## Duplicated visits


```{r}
duplicated_entires <- 
  wellness_meta |> 
  group_by(Subject) |> 
  count(Visit) |> 
  filter(n > 1) 

DAid_exclude <- c("DA11971", "DA12092", "DA12126")

wellness_data <-
  wellness_data |>
  filter(!DAid %in% DAid_exclude)

wellness_meta <-
  wellness_meta |>
  filter(!DAid %in% DAid_exclude)
```

## Remove samples with fewer visits

```{r}
number_of_visits <- 
  wellness_meta |> 
  group_by(Subject) |> 
  summarise(Number_of_visits = n_distinct(Visit)) |> 
  arrange(Number_of_visits)  

#write_tsv(number_of_visits, savepath("number_of_visits.tsv"))

subjects_limited_visits <- 
  number_of_visits |> 
  filter(Number_of_visits < 3) |>
  pull(Subject)

DAid_exclude_limited_visits <- 
  wellness_meta |> 
  filter(Subject %in% subjects_limited_visits) |> 
  pull(DAid)

# Exclusion of subjects with < 3 visits
wellness_data <-
  wellness_data |>
  filter(!DAid %in% DAid_exclude_limited_visits)

wellness_meta <-
  wellness_meta |>
  filter(!DAid %in% DAid_exclude_limited_visits)
```

## PCA

```{r}

```

## LOD

```{r}
lod_sample_dat <- 
  wellness_data |> 
  group_by(DAid) |> 
  count(above_LOD) 

lod_sample_dat_order <- 
  lod_sample_dat |> 
  filter(above_LOD == "Yes") |>
  arrange(-n)

lod_sample_dat|> 
  mutate(DAid = factor(DAid, levels = lod_sample_dat_order$DAid)) |>
  ggplot(aes(DAid, n, fill = above_LOD)) +
  geom_col() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) 
```

## Save

```{r}
write_tsv(wellness_data, "data/final_data/HPA/v24_2/wellness_data_ht_phase2.tsv")
write_tsv(wellness_meta, "data/final_data/HPA/v24_2/wellness_meta_ht_phase2.tsv")
```


# BAMSE data

```{r}
bamse_meta <- 
  manifest |> 
  filter(DAid %in% ht_data$DAid,
         !grepl("lung_function", Diagnose),
         !grepl("back-up", Diagnose),
         Cohort == "BAMS") |> 
  mutate(Diagnose = gsub("_random", "", Diagnose),
         Visit = factor(Diagnose, levels = c("4", "8", "16", "24")),
         Subject = str_extract(`Vial barcode`, "(?<=_)[0-9]+")) |> 
  select(DAid, Age, Sex, Visit, Subject)

bamse_data <- 
  ht_data |> 
  filter(DAid %in% bamse_meta$DAid)
```


## LOD

```{r}
lod_sample_dat <- 
  bamse_data |> 
  group_by(DAid) |> 
  count(above_LOD) 

lod_sample_dat_order <- 
  lod_sample_dat |> 
  filter(above_LOD == "Yes") |>
  arrange(-n)

lod_sample_dat|> 
  mutate(DAid = factor(DAid, levels = lod_sample_dat_order$DAid)) |>
  ggplot(aes(DAid, n, fill = above_LOD)) +
  geom_col() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) 
```

## Save

```{r}
write_tsv(bamse_data, "data/final_data/HPA/v24_2/bamse_data_ht_phase2.tsv")
write_tsv(bamse_meta, "data/final_data/HPA/v24_2/bamse_meta_ht_phase2.tsv")
```


